// Bindings generated by `windows-bindgen` 0.63.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

windows_core::imp::define_interface!(
    IXamlOptionalChanges,
    IXamlOptionalChanges_Vtbl,
    0x387572ae_ac51_5cb0_8317_2d6e118bea6a
);
impl windows_core::RuntimeType for IXamlOptionalChanges {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IXamlOptionalChanges {
    const NAME: &'static str = "Microsoft.UI.Xaml.Settings.IXamlOptionalChanges";
}
pub trait IXamlOptionalChanges_Impl: windows_core::IUnknownImpl {}
impl IXamlOptionalChanges_Vtbl {
    pub const fn new<Identity: IXamlOptionalChanges_Impl, const OFFSET: isize>() -> Self {
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<Identity, IXamlOptionalChanges, OFFSET>(
            ),
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IXamlOptionalChanges as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IXamlOptionalChanges_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
}
windows_core::imp::define_interface!(
    IXamlOptionalChangesStatics,
    IXamlOptionalChangesStatics_Vtbl,
    0xedb65323_1884_51c9_8b79_719554de4dd9
);
impl windows_core::RuntimeType for IXamlOptionalChangesStatics {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_interface::<Self>();
}
impl windows_core::RuntimeName for IXamlOptionalChangesStatics {
    const NAME: &'static str = "Microsoft.UI.Xaml.Settings.IXamlOptionalChangesStatics";
}
pub trait IXamlOptionalChangesStatics_Impl: windows_core::IUnknownImpl {
    fn EnableChange(&self, changeId: XamlChangeId) -> windows_core::Result<bool>;
    fn DisableChange(&self, changeId: XamlChangeId) -> windows_core::Result<bool>;
    fn IsChangeEnabled(&self, changeId: XamlChangeId) -> windows_core::Result<bool>;
    fn Lock(&self) -> windows_core::Result<bool>;
    fn IsLocked(&self) -> windows_core::Result<bool>;
}
impl IXamlOptionalChangesStatics_Vtbl {
    pub const fn new<Identity: IXamlOptionalChangesStatics_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn EnableChange<
            Identity: IXamlOptionalChangesStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            changeid: XamlChangeId,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IXamlOptionalChangesStatics_Impl::EnableChange(this, changeid) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn DisableChange<
            Identity: IXamlOptionalChangesStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            changeid: XamlChangeId,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IXamlOptionalChangesStatics_Impl::DisableChange(this, changeid) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn IsChangeEnabled<
            Identity: IXamlOptionalChangesStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            changeid: XamlChangeId,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IXamlOptionalChangesStatics_Impl::IsChangeEnabled(this, changeid) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn Lock<
            Identity: IXamlOptionalChangesStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IXamlOptionalChangesStatics_Impl::Lock(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn IsLocked<
            Identity: IXamlOptionalChangesStatics_Impl,
            const OFFSET: isize,
        >(
            this: *mut core::ffi::c_void,
            result__: *mut bool,
        ) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity =
                    &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match IXamlOptionalChangesStatics_Impl::IsLocked(this) {
                    Ok(ok__) => {
                        result__.write(core::mem::transmute_copy(&ok__));
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        Self {
            base__: windows_core::IInspectable_Vtbl::new::<
                Identity,
                IXamlOptionalChangesStatics,
                OFFSET,
            >(),
            EnableChange: EnableChange::<Identity, OFFSET>,
            DisableChange: DisableChange::<Identity, OFFSET>,
            IsChangeEnabled: IsChangeEnabled::<Identity, OFFSET>,
            Lock: Lock::<Identity, OFFSET>,
            IsLocked: IsLocked::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<IXamlOptionalChangesStatics as windows_core::Interface>::IID
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct IXamlOptionalChangesStatics_Vtbl {
    pub base__: windows_core::IInspectable_Vtbl,
    pub EnableChange: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        XamlChangeId,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub DisableChange: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        XamlChangeId,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub IsChangeEnabled: unsafe extern "system" fn(
        *mut core::ffi::c_void,
        XamlChangeId,
        *mut bool,
    ) -> windows_core::HRESULT,
    pub Lock: unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
    pub IsLocked:
        unsafe extern "system" fn(*mut core::ffi::c_void, *mut bool) -> windows_core::HRESULT,
}
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct XamlChangeId(pub i32);
impl XamlChangeId {
    pub const _Reserved: Self = Self(0i32);
    pub const IconNoGridOptimization: Self = Self(61276805i32);
    pub const OptimizeApplyStyles: Self = Self(61697456i32);
    pub const DefaultStyleOptimizations: Self = Self(60995620i32);
    pub const DeferContextFlyoutInit: Self = Self(61098986i32);
}
impl windows_core::TypeKind for XamlChangeId {
    type TypeKind = windows_core::CopyType;
}
impl windows_core::RuntimeType for XamlChangeId {
    const SIGNATURE: windows_core::imp::ConstBuffer = windows_core::imp::ConstBuffer::from_slice(
        b"enum(Microsoft.UI.Xaml.Settings.XamlChangeId;i4)",
    );
}
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct XamlOptionalChanges(windows_core::IUnknown);
windows_core::imp::interface_hierarchy!(
    XamlOptionalChanges,
    windows_core::IUnknown,
    windows_core::IInspectable
);
impl XamlOptionalChanges {
    pub fn EnableChange(changeid: XamlChangeId) -> windows_core::Result<bool> {
        Self::IXamlOptionalChangesStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).EnableChange)(
                windows_core::Interface::as_raw(this),
                changeid,
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn DisableChange(changeid: XamlChangeId) -> windows_core::Result<bool> {
        Self::IXamlOptionalChangesStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).DisableChange)(
                windows_core::Interface::as_raw(this),
                changeid,
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn IsChangeEnabled(changeid: XamlChangeId) -> windows_core::Result<bool> {
        Self::IXamlOptionalChangesStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsChangeEnabled)(
                windows_core::Interface::as_raw(this),
                changeid,
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn Lock() -> windows_core::Result<bool> {
        Self::IXamlOptionalChangesStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).Lock)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    pub fn IsLocked() -> windows_core::Result<bool> {
        Self::IXamlOptionalChangesStatics(|this| unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(this).IsLocked)(
                windows_core::Interface::as_raw(this),
                &mut result__,
            )
            .map(|| result__)
        })
    }
    fn IXamlOptionalChangesStatics<
        R,
        F: FnOnce(&IXamlOptionalChangesStatics) -> windows_core::Result<R>,
    >(
        callback: F,
    ) -> windows_core::Result<R> {
        static SHARED: windows_core::imp::FactoryCache<
            XamlOptionalChanges,
            IXamlOptionalChangesStatics,
        > = windows_core::imp::FactoryCache::new();
        SHARED.call(callback)
    }
}
impl windows_core::RuntimeType for XamlOptionalChanges {
    const SIGNATURE: windows_core::imp::ConstBuffer =
        windows_core::imp::ConstBuffer::for_class::<Self, IXamlOptionalChanges>();
}
unsafe impl windows_core::Interface for XamlOptionalChanges {
    type Vtable = <IXamlOptionalChanges as windows_core::Interface>::Vtable;
    const IID: windows_core::GUID = <IXamlOptionalChanges as windows_core::Interface>::IID;
}
impl windows_core::RuntimeName for XamlOptionalChanges {
    const NAME: &'static str = "Microsoft.UI.Xaml.Settings.XamlOptionalChanges";
}
unsafe impl Send for XamlOptionalChanges {}
unsafe impl Sync for XamlOptionalChanges {}
