[package]
name = "bindgen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
memmap2 = "0.9.5"
windows-bindgen = { git = "https://github.com/microsoft/windows-rs.git", tag = "0.60.0" }
